PREFIX cap: <https://hcis.io/ontology/aicapstone/2026/>
PREFIX g08: <https://hcis.io/ontology/aicapstone/2026/group08/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?obj ?label ?role ?color ?type
WHERE {
  ?obj cap:hasTaskRole ?role .
  OPTIONAL { ?obj cap:hasObjectLabel ?label . }
  OPTIONAL { ?obj cap:hasColor       ?color . }
  OPTIONAL { ?obj a                  ?type  .
             FILTER(?type IN (
               g08:GraspableObject,
               g08:ColorSortableObject
             )) }
}
ORDER BY ?role ?obj
